/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=1*/;
/*!40019 SET @@session.max_insert_delayed_threads=0*/;
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
DELIMITER /*!*/;
# at 4
#210326 14:40:15 server id 1  end_log_pos 249 	Start: binlog v 4, server v 10.1.38-MariaDB created 210326 14:40:15 at startup
# Warning: this binlog is either in use or was not closed properly.
ROLLBACK/*!*/;
BINLOG '
H8hdYA8BAAAA9QAAAPkAAAABAAQAMTAuMS4zOC1NYXJpYURCAGxvZwAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAfyF1gEzgNAAgAEgAEBAQEEgAA3QAEGggAAAAICAgCAAAACgoKAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAEEwQAAAkdJiU=
'/*!*/;
# at 249
#210326 14:40:15 server id 1  end_log_pos 274 	Gtid list []
# at 274
#210326 14:40:15 server id 1  end_log_pos 310 	Binlog checkpoint binlog.000001
# at 310
#210326 14:40:49 server id 1  end_log_pos 348 	GTID 0-1-1 ddl
/*!100101 SET @@session.skip_parallel_replication=0*//*!*/;
/*!100001 SET @@session.gtid_domain_id=0*//*!*/;
/*!100001 SET @@session.server_id=1*//*!*/;
/*!100001 SET @@session.gtid_seq_no=1*//*!*/;
# at 348
#210326 14:40:49 server id 1  end_log_pos 499 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758849/*!*/;
SET @@session.pseudo_thread_id=3/*!*/;
SET @@session.foreign_key_checks=0, @@session.sql_auto_is_null=0, @@session.unique_checks=0, @@session.autocommit=1/*!*/;
SET @@session.sql_mode=524288/*!*/;
SET @@session.auto_increment_increment=1, @@session.auto_increment_offset=1/*!*/;
/*!\C utf8 *//*!*/;
SET @@session.character_set_client=33,@@session.collation_connection=33,@@session.collation_server=8/*!*/;
SET @@session.lc_time_names=0/*!*/;
SET @@session.collation_database=DEFAULT/*!*/;
CREATE DATABASE /*!32312 IF NOT EXISTS*/ `ijdb` /*!40100 DEFAULT CHARACTER SET latin1 */
/*!*/;
# at 499
#210326 14:40:49 server id 1  end_log_pos 537 	GTID 0-1-2 ddl
/*!100001 SET @@session.gtid_seq_no=2*//*!*/;
# at 537
#210326 14:40:49 server id 1  end_log_pos 655 	Query	thread_id=3	exec_time=0	error_code=0
use `ijdb`/*!*/;
SET TIMESTAMP=1616758849/*!*/;
DROP TABLE IF EXISTS `author` /* generated by server */
/*!*/;
# at 655
#210326 14:40:49 server id 1  end_log_pos 693 	GTID 0-1-3 ddl
/*!100001 SET @@session.gtid_seq_no=3*//*!*/;
# at 693
#210326 14:40:49 server id 1  end_log_pos 997 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758849/*!*/;
CREATE TABLE `author` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1
/*!*/;
# at 997
#210326 14:40:49 server id 1  end_log_pos 1035 	GTID 0-1-4 ddl
/*!100001 SET @@session.gtid_seq_no=4*//*!*/;
# at 1035
#210326 14:40:49 server id 1  end_log_pos 1143 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758849/*!*/;
/*!40000 ALTER TABLE `author` DISABLE KEYS */
/*!*/;
# at 1143
#210326 14:40:49 server id 1  end_log_pos 1181 	GTID 0-1-5 trans
/*!100001 SET @@session.gtid_seq_no=5*//*!*/;
BEGIN
/*!*/;
# at 1181
#210326 14:40:49 server id 1  end_log_pos 1555 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758849/*!*/;
INSERT INTO `author` VALUES (1,'igor','igorwho@yandex.ru','$2y$10$9hvKqOLzDvQDpz1f6oGLHe1VvBqB0ZC3gr7eLv9Cqk9jdd/ugmdba'),(2,'marduk','marduk@gmail.com','$2y$10$Z8IQVHUtQHmrAUloQuW6VuSZmnPoVLPUjYsXFryXZSO4LK6klYvYy'),(3,'burzum','burzum@gmail.com','$2y$10$vk8NIpv9kPRO5lNNcOcm3Om5T6e3asJ4XMjJ8Mxy4jKR0fl70PnsK')
/*!*/;
# at 1555
#210326 14:40:49 server id 1  end_log_pos 1582 	Xid = 21
COMMIT/*!*/;
# at 1582
#210326 14:40:49 server id 1  end_log_pos 1620 	GTID 0-1-6 ddl
/*!100001 SET @@session.gtid_seq_no=6*//*!*/;
# at 1620
#210326 14:40:49 server id 1  end_log_pos 1727 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758849/*!*/;
/*!40000 ALTER TABLE `author` ENABLE KEYS */
/*!*/;
# at 1727
#210326 14:40:49 server id 1  end_log_pos 1765 	GTID 0-1-7 ddl
/*!100001 SET @@session.gtid_seq_no=7*//*!*/;
# at 1765
#210326 14:40:49 server id 1  end_log_pos 1885 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758849/*!*/;
DROP TABLE IF EXISTS `category` /* generated by server */
/*!*/;
# at 1885
#210326 14:40:49 server id 1  end_log_pos 1923 	GTID 0-1-8 ddl
/*!100001 SET @@session.gtid_seq_no=8*//*!*/;
# at 1923
#210326 14:40:49 server id 1  end_log_pos 2143 	Query	thread_id=3	exec_time=1	error_code=0
SET TIMESTAMP=1616758849/*!*/;
CREATE TABLE `category` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
/*!*/;
# at 2143
#210326 14:40:50 server id 1  end_log_pos 2181 	GTID 0-1-9 ddl
/*!100001 SET @@session.gtid_seq_no=9*//*!*/;
# at 2181
#210326 14:40:50 server id 1  end_log_pos 2291 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758850/*!*/;
/*!40000 ALTER TABLE `category` DISABLE KEYS */
/*!*/;
# at 2291
#210326 14:40:50 server id 1  end_log_pos 2329 	GTID 0-1-10 ddl
/*!100001 SET @@session.gtid_seq_no=10*//*!*/;
# at 2329
#210326 14:40:50 server id 1  end_log_pos 2438 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758850/*!*/;
/*!40000 ALTER TABLE `category` ENABLE KEYS */
/*!*/;
# at 2438
#210326 14:40:50 server id 1  end_log_pos 2476 	GTID 0-1-11 ddl
/*!100001 SET @@session.gtid_seq_no=11*//*!*/;
# at 2476
#210326 14:40:50 server id 1  end_log_pos 2592 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758850/*!*/;
DROP TABLE IF EXISTS `joke` /* generated by server */
/*!*/;
# at 2592
#210326 14:40:50 server id 1  end_log_pos 2630 	GTID 0-1-12 ddl
/*!100001 SET @@session.gtid_seq_no=12*//*!*/;
# at 2630
#210326 14:40:50 server id 1  end_log_pos 2941 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758850/*!*/;
CREATE TABLE `joke` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `text` longtext NOT NULL,
  `timestamp` datetime DEFAULT CURRENT_TIMESTAMP,
  `author_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1
/*!*/;
# at 2941
#210326 14:40:50 server id 1  end_log_pos 2979 	GTID 0-1-13 ddl
/*!100001 SET @@session.gtid_seq_no=13*//*!*/;
# at 2979
#210326 14:40:50 server id 1  end_log_pos 3085 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758850/*!*/;
/*!40000 ALTER TABLE `joke` DISABLE KEYS */
/*!*/;
# at 3085
#210326 14:40:50 server id 1  end_log_pos 3123 	GTID 0-1-14 trans
/*!100001 SET @@session.gtid_seq_no=14*//*!*/;
BEGIN
/*!*/;
# at 3123
#210326 14:40:50 server id 1  end_log_pos 3465 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758850/*!*/;
INSERT INTO `joke` VALUES (1,'My salary.','2021-03-26 10:45:25',1),(2,'Kolobok hanged.','2021-03-26 10:46:00',1),(3,'Our albums.','2021-03-26 10:46:29',2),(4,'Burning churches.','2021-03-26 10:47:03',3),(5,'Black metal.','2021-03-26 10:48:39',3),(6,'DPR','2021-03-26 10:49:08',1)
/*!*/;
# at 3465
#210326 14:40:50 server id 1  end_log_pos 3492 	Xid = 40
COMMIT/*!*/;
# at 3492
#210326 14:40:50 server id 1  end_log_pos 3530 	GTID 0-1-15 ddl
/*!100001 SET @@session.gtid_seq_no=15*//*!*/;
# at 3530
#210326 14:40:50 server id 1  end_log_pos 3635 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758850/*!*/;
/*!40000 ALTER TABLE `joke` ENABLE KEYS */
/*!*/;
# at 3635
#210326 14:40:50 server id 1  end_log_pos 3673 	GTID 0-1-16 ddl
/*!100001 SET @@session.gtid_seq_no=16*//*!*/;
# at 3673
#210326 14:40:50 server id 1  end_log_pos 3799 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758850/*!*/;
DROP TABLE IF EXISTS `joke__category` /* generated by server */
/*!*/;
# at 3799
#210326 14:40:50 server id 1  end_log_pos 3837 	GTID 0-1-17 ddl
/*!100001 SET @@session.gtid_seq_no=17*//*!*/;
# at 3837
#210326 14:40:50 server id 1  end_log_pos 4074 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758850/*!*/;
CREATE TABLE `joke__category` (
  `joke_id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL,
  PRIMARY KEY (`joke_id`,`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
/*!*/;
# at 4074
#210326 14:40:50 server id 1  end_log_pos 4112 	GTID 0-1-18 ddl
/*!100001 SET @@session.gtid_seq_no=18*//*!*/;
# at 4112
#210326 14:40:50 server id 1  end_log_pos 4228 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758850/*!*/;
/*!40000 ALTER TABLE `joke__category` DISABLE KEYS */
/*!*/;
# at 4228
#210326 14:40:50 server id 1  end_log_pos 4266 	GTID 0-1-19 ddl
/*!100001 SET @@session.gtid_seq_no=19*//*!*/;
# at 4266
#210326 14:40:50 server id 1  end_log_pos 4381 	Query	thread_id=3	exec_time=0	error_code=0
SET TIMESTAMP=1616758850/*!*/;
/*!40000 ALTER TABLE `joke__category` ENABLE KEYS */
/*!*/;
# at 4381
#210326 14:41:06 server id 1  end_log_pos 4419 	GTID 0-1-20 trans
/*!100001 SET @@session.gtid_seq_no=20*//*!*/;
BEGIN
/*!*/;
# at 4419
#210326 14:41:06 server id 1  end_log_pos 4447 	Intvar
SET INSERT_ID=7/*!*/;
# at 4447
#210326 14:41:06 server id 1  end_log_pos 4590 	Query	thread_id=9	exec_time=0	error_code=0
SET TIMESTAMP=1616758866.938476/*!*/;
SET @@session.foreign_key_checks=1, @@session.unique_checks=1/*!*/;
SET @@session.sql_mode=1342177280/*!*/;
SET @@session.time_zone='SYSTEM'/*!*/;
INSERT INTO `joke` (`id`,`text`,`author_id`) VALUES (NULL,'One','1')
/*!*/;
# at 4590
#210326 14:41:06 server id 1  end_log_pos 4617 	Xid = 113
COMMIT/*!*/;
# at 4617
#210326 14:41:16 server id 1  end_log_pos 4655 	GTID 0-1-21 trans
/*!100001 SET @@session.gtid_seq_no=21*//*!*/;
BEGIN
/*!*/;
# at 4655
#210326 14:41:16 server id 1  end_log_pos 4683 	Intvar
SET INSERT_ID=8/*!*/;
# at 4683
#210326 14:41:16 server id 1  end_log_pos 4826 	Query	thread_id=12	exec_time=0	error_code=0
SET TIMESTAMP=1616758876.954101/*!*/;
INSERT INTO `joke` (`id`,`text`,`author_id`) VALUES (NULL,'Two','1')
/*!*/;
# at 4826
#210326 14:41:16 server id 1  end_log_pos 4853 	Xid = 137
COMMIT/*!*/;
# at 4853
#210326 14:41:25 server id 1  end_log_pos 4891 	GTID 0-1-22 trans
/*!100001 SET @@session.gtid_seq_no=22*//*!*/;
BEGIN
/*!*/;
# at 4891
#210326 14:41:25 server id 1  end_log_pos 4919 	Intvar
SET INSERT_ID=9/*!*/;
# at 4919
#210326 14:41:25 server id 1  end_log_pos 5064 	Query	thread_id=15	exec_time=0	error_code=0
SET TIMESTAMP=1616758885.916992/*!*/;
INSERT INTO `joke` (`id`,`text`,`author_id`) VALUES (NULL,'Three','1')
/*!*/;
# at 5064
#210326 14:41:25 server id 1  end_log_pos 5091 	Xid = 162
COMMIT/*!*/;
# at 5091
#210326 14:41:47 server id 1  end_log_pos 5129 	GTID 0-1-23 trans
/*!100001 SET @@session.gtid_seq_no=23*//*!*/;
BEGIN
/*!*/;
# at 5129
#210326 14:41:47 server id 1  end_log_pos 5364 	Query	thread_id=25	exec_time=0	error_code=0
SET TIMESTAMP=1616758907.743164/*!*/;
/*!\C latin1 *//*!*/;
SET @@session.character_set_client=8,@@session.collation_connection=8,@@session.collation_server=8/*!*/;
UPDATE `phpmyadmin`.`pma__userconfig` SET `timevalue` = NOW(), `config_data` = '{\"Console\\/Mode\":\"collapse\",\"NavigationWidth\":215}' WHERE `username` = 'root'
/*!*/;
# at 5364
#210326 14:41:47 server id 1  end_log_pos 5391 	Xid = 232
COMMIT/*!*/;
DELIMITER ;
# End of log file
ROLLBACK /* added by mysqlbinlog */;
/*!50003 SET COMPLETION_TYPE=@OLD_COMPLETION_TYPE*/;
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=0*/;
